### ISSUE TITLE
Multi-géométries interdites

### ISSUE THREAD

**Issue by maltaesousa** [sitn/geoshop2#120]

**Comment by kalbermattenm** [comment]
Tu peux me donner quelques détails à ce sujet ?

Je ne comprends pas comment produire une multi-géométrie??

**Comment by maltaesousa** [comment]
Je n'ai pas une liste exhaustive des cas mais:

1. Dessiner un polygone
2. Rechercher une parcelle
3. Un nouveau polygone apparaît, l'ancien polygone dessiné reste.

Pour bien, il faudrait que cette couche n'ait qu'un polygone à la fois.
