### ISSUE TITLE
Poubelle supprime tout ce qui est dessiné sur la carte

### ISSUE THREAD

**Issue by maltaesousa** [sitn/geoshop2#121]

**Comment by kalbermattenm** [comment]
Tu peux me donner quelques détails à ce sujet ?

N'est-ce pas à quoi la poubelle sert ?

**Comment by maltaesousa** [comment]
Ouais mais pour l'instant dans le cas de doubles géométries, ça ne supprime pas tout, ça supprime seulement la dernière géométrie dessinée.

Peut-être qu'il faut d'abord régler #120 et que le problème ne se posera plus
