### ISSUE TITLE
Périmètres de commande au format A4 pour les 3 échelles cadastrales

### ISSUE THREAD

**Issue by maltaesousa** [sitn/geoshop2#122]
TODO:

- [x] use min-width for dialog
- [x] allow rotation & translation on map
- [x] disable other buttons / or everything else while format dialog is open (can click twice on page format button thus opening twice dialog)
- [x] Geometry sent is invalid

**Comment by maltaesousa** [comment]
![format](https://user-images.githubusercontent.com/3328875/97274176-901b3400-1834-11eb-9db8-b950eeb821f9.png)

SVG icon: [format.zip](https://github.com/sitn/geoshop2/files/5443818/format.zip)

then a modal or a panel opens an lets choose which format, which scale. When pressing ok draws rectangle on map and zooms to it. Rectangle can be rotated. rectangle replaces any existing geometry. using the tool again replaces any previous rectangle but previous parameters (format and scale are kept)

**Comment by kalbermattenm** [comment]
The proposed paper size must be inspired by the current getCap json which can be found here: https://github.com/sitn/geoshop/blob/master/geoshop/static/print/info_num.json

**Comment by kalbermattenm** [comment]
I while try to write some kind of a use-case and its technical sheet in order to be sure about the implemented logic...

**Comment by kalbermattenm** [comment]
Do you mind if I use https://github.com/Viglino/ol-ext via npm?

It greatly simplifies using the feature interaction, otherwise I am mainly going to rewrite the whole thing.

**Comment by maltaesousa** [comment]
We should definitely use it :)
