### ISSUE TITLE
Product : search : problème d'encodage (accent ?) 

### ISSUE THREAD

**Issue by endorria** [sitn/geoshop2#136]
Lors d'une recherche de produit depuis le client, la valeur du search est encodée => côté serveur cela ne semble pas être géré
ex : https://sitn.ne.ch/geoshop2_prepub_api/product/?search=MO07%20-%20Objets%20divers%20et%20%C3%A9l%C3%A9ments%20lin%C3%A9aires%20-%20lin%C3%A9aires
=> devrait sortir le produit : https://sitn.ne.ch/geoshop2_prepub_api/product/184/

**Comment by maltaesousa** [comment]
Le problème est résolu en prepub. J'en ai résolu un autre qui affichait les produits DEPRECATED dans la liste des products. Fait que ton lien renvoie toujours rien mais maintenant c'est normal.

Voici un autre lien avec les accents:
https://sitn.ne.ch/geoshop2_prepub_api/product/?search=MO%20-%20PFP%20et%20b%C3%A2timents
